name: Backend Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
            - develop

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Setup Java
              uses: actions/setup-java@v2
              with:
                  distribution: temurin
                  java-version: 21

            - name: Build with Maven
              working-directory: .
              run: mvn clean install

            - name: Run tests
              working-directory: .
              run: mvn test
